app:
  timezone: Europe/Moscow
  auth:
    jwt-secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    access-token-expiration: 15m
    refresh-token-expiration: 30d
    secure: true
    same-site: 'Strict'

spring:
  application:
    name: mocknet
  datasource:
    url: jdbc:postgresql://localhost:5432/mocknet-db
    username: mocknet
    password: mocknet
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always